---

- block:
    - name: nginx https configuration
      ansible.builtin.template:
        src: "{{ hashlookupserver_nginx_template }}"
        dest: "{{ apache_sitedir }}/hashlookup-server"
        owner: '0'
        group: '0'
        mode: '0644'
      notify:
        - restart nginx
    - name: enable https
      ansible.builtin.file:
        src: "{{ apache_sitedir }}/hashlookup-server"
        dest: "/etc/nginx/sites-enabled/hashlookup-server"
        state: link
        mode: '0644'
      notify:
        - restart nginx
  when: ansible_os_family == 'Debian'
