---

- name: Ensure systemd folder exists
  file:
    dest: /etc/systemd/system
    state: directory
    mode: '0755'

- name: Ensure systemd unit files are configured
  template:
    src: "systemd-{{ item }}.conf.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: '0644'
  loop:
    - kvrocks
    - hashlookupserver
  notify:
    - reload systemd
    - restart kvrocks
    - restart hashlookup-server

- name: Ensure services are enabled and started
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - kvrocks
    - hashlookupserver
