---

- name: Ensure systemd folder exists
  ansible.builtin.file:
    dest: /etc/systemd/system
    state: directory
    mode: '0755'

- name: Ensure systemd unit files are configured
  ansible.builtin.template:
    src: "systemd-{{ item }}.conf.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: '0644'
  loop:
    - kvrocks
    - hashlookupserver
  notify:
    - Reload systemd
    - Restart kvrocks
    - Restart hashlookup-server

- name: Ensure services are enabled and started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - kvrocks
    - hashlookupserver
