---
name: AnsibleCI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:  # run weekly, every Thursday 01:00
    - cron: '0 1 * * 4'

permissions: {}

jobs:
  build:

    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.8]
        molecule_distro:
          - 'rockylinux:9'
          - 'ubuntu:24.04'
          - 'ubuntu:22.04'
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      MOLECULE_NO_LOG: "false"
      ANSIBLE_ROLE: juju4.hashlookupserver

    steps:
      - uses: actions/checkout@v5
        with:
          path: ${{ env.ANSIBLE_ROLE }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule[docker] ansible-lint flake8 testinfra ansible
          mkdir -p $HOME/.ansible/roles && ln -s $GITHUB_WORKSPACE/$ANSIBLE_ROLE $HOME/.ansible/roles/
      - name: Fetch central settings repository
        run: |
          export settings_repo="https://raw.githubusercontent.com/juju4/ansible-ci-settings/main"
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          set -x
          curl -o requirements.txt "$settings_repo/requirements.txt"
          curl -o .ansible-lint "$settings_repo/.ansible-lint"
          curl -o .yamllint "$settings_repo/.yamllint"
          pip install -r requirements.txt
        continue-on-error: true
      - name: Environment
        run: |
          pwd
          env
          find -ls
          df -h
      - name: Free disk space
        run: |
          set -x
          ls /usr/local
          for d in /usr/local/*; do du -hx "$d" | tail -1; done
          ls /opt
          for d in /opt/*; do du -hx "$d" | tail -1; done
          sudo rm -Rf /usr/local/lib/android
          sudo rm -Rf /home/linuxbrew
          df -h
          sudo docker image prune -a -f
          df -h
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
