---
name: importer

on:
  push:
  pull_request:
  schedule:  # run weekly, every Thursday 01:00
    - cron: '0 1 * * 4'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.8]
        molecule_distro:
          - 'centos:8'
          - 'ubuntu:20.04'
    env:
      ANSIBLE_CALLBACK_ENABLED: profile_tasks
      MOLECULE_NO_LOG: "false"

    steps:
      - uses: actions/checkout@v2
        with:
          path: juju4.hashlookupserver
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule[docker] ansible-lint flake8 testinfra ansible
          mkdir -p $HOME/.ansible/roles && ln -s $GITHUB_WORKSPACE/juju4.hashlookupserver $HOME/.ansible/roles/
      - name: Environment
        run: |
          pwd
          env
          find -ls
      - name: importer test
        run: |
          apt-get install -y gcc libfuzzy-dev libmagic-dev python3 python3-pip
          git clone https://github.com/hashlookup/hashlookup-importer
          cd hashlookup-importer
          pip3 install -r REQUIREMENTS
          python3 hashlookup-importer.py -s TEST -d .
