---
name: importer

on:
  push:
  pull_request:
  schedule:  # run weekly, every Thursday 01:00
    - cron: '0 1 * * 4'

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    continue-on-error: true  # experimental
    strategy:
      fail-fast: false
      max-parallel: 4
    env:
      ANSIBLE_CALLBACK_ENABLED: profile_tasks

    steps:
      - uses: actions/checkout@v3
        with:
          path: juju4.hashlookupserver
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint
          which ansible
          pip3 install ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ls -l /opt/hostedtoolcache/Python/3.9.1/x64/bin || true
          echo "/opt/hostedtoolcache/Python/3.9.1/x64/bin" >> $GITHUB_PATH
          ansible --version
          cd $GITHUB_WORKSPACE/juju4.hashlookupserver
          ansible-galaxy install -r molecule/default/requirements.yml
          { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../:/home/runner/.ansible/roles'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: Environment
        run: |
          pwd
          env
          find -ls
      - name: hashlookup-server install
        run: |
          cd $GITHUB_WORKSPACE/juju4.hashlookupserver && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: importer test
        run: |
          set -x
          sudo apt-get install -y gcc libfuzzy-dev libmagic-dev python3 python3-pip
          git clone https://github.com/hashlookup/hashlookup-lib.git
          pip3 install ./hashlookup-lib
          git clone https://github.com/hashlookup/hashlookup-importer
          cd hashlookup-importer
          pip3 install -r REQUIREMENTS
          cd bin
          python3 hashlookup-importer.py -s TEST -d .
